on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH
        uses: yitianyigexiangfa/ssh-scp-ssh-pipelines@v1.1.5
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          first_ssh: |
            rm -rf ./qexat/*
          scp: |
            ./src/* => ./qexat/
